# Generated by Django 4.0.2 on 2022-05-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0007_alter_envioguia_table'),
        ('Conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='envios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Call.envioguia'),
        ),
    ]
