# Generated by Django 4.0.2 on 2022-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0002_entrega_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='observacion',
            field=models.TextField(default=''),
        ),
    ]
