# Generated by Django 4.0.2 on 2022-05-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conductor', '0005_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observaciones',
            name='entrega',
        ),
    ]
