# Generated by Django 4.0.2 on 2022-04-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0002_departamento_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numueroguia', models.CharField(max_length=50)),
                ('identificacionRemi', models.CharField(max_length=50)),
                ('nombreRemi', models.CharField(max_length=50)),
                ('direccionRemi', models.TextField()),
                ('telefonoRemi', models.CharField(max_length=50)),
                ('correoRemi', models.EmailField(max_length=254)),
                ('identificacionDesti', models.CharField(max_length=50)),
                ('nombreDesti', models.CharField(max_length=50)),
                ('direccionDesti', models.TextField()),
                ('telefonoDesti', models.CharField(max_length=50)),
                ('correoDesti', models.EmailField(max_length=254)),
                ('peso', models.CharField(max_length=50)),
                ('alto', models.CharField(max_length=50)),
                ('ancho', models.CharField(max_length=50)),
                ('largo', models.CharField(max_length=50)),
                ('contiene', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ciudadDesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadDesti', to='Call.municipio')),
                ('ciudadRemi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadRemi', to='Call.municipio')),
                ('formapagp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Call.formapago')),
                ('tipoIdDesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoIdDesti', to='Call.tipoidentificacion')),
                ('tipoIdRemitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoIdRemitente', to='Call.tipoidentificacion')),
                ('tipoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Call.tiposervicio')),
            ],
            options={
                'verbose_name': 'Envio de Guia',
                'verbose_name_plural': 'Envios de Guias',
            },
        ),
    ]
