# Generated by Django 4.0.2 on 2022-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0004_envioguia_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioguia',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
