# Generated by Django 4.0.2 on 2022-04-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0005_envioguia_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='envioguia',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
