# Generated by Django 4.0.2 on 2022-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0006_envioguia_asignado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='envioguia',
            table='EnvioGuia',
        ),
    ]
