# Generated by Django 4.0.2 on 2022-05-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Call', '0008_envioguia_entrega_envioguia_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envioguia',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='envioguia',
            name='observacion',
        ),
    ]
