# Generated by Django 4.0.2 on 2022-04-11 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipovehiculo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
